### ISSUE TITLE
Explore data with a Data Explorer pool

### ISSUE THREAD

**Issue by hendrobagoes** [MicrosoftLearning/dp-203-azure-data-engineer#12]
# Module: Explore data with a Data Explorer pool
#### Step: 06

Description of issue

Hi, I was trying to follow the step by step outlined in the repo and get to part of "Explore data with a Data Explorer Pool". I couldn't find the ingest-data script that mention in step 6 below. Was there any step I missed or the document is misssing some steps?

Switch to the Develop page, and in the KQL scripts list, select ingest-data. When the script opens, note that it contains two statements:

Repro steps:

1.
1.
1.

**Comment by GraemeMalcolm** [comment]
The script should have been uploaded by the setup script. However, we've noted that occasionally it fails. You can find the script in this repo at https://github.com/MicrosoftLearning/dp-203-azure-data-engineer/blob/master/Allfiles/labs/01/files/ingest-data.kql

We're doing some testing to see if we can find out why the API occasionally fails to upload the script, and we'll do what we can to fix it.

**Comment by hendrobagoes** [comment]
Thanks GraemeMalcolm, much appreciate your fast response.

**Comment by GraemeMalcolm** [comment]
At this point, the most expedient/reliable thing to do seems to be to have the students create the script and manually enter the code as part of the exercise. The updated instructions have been pushed.Interestingly, the issue seems to be constrained to the Skillable cloudslice - in a regular Azure subscription the file seems to be successfully created (at least in my testing). I'll follow up with Skillable to see if we can get to the root of it, but for now the alternative instructions should unblock the issue.
