### ISSUE TITLE
Lab 9, provisioning setup script throws error

### ISSUE THREAD

**Issue by VEshelbyMTT** [MicrosoftLearning/dp-203-azure-data-engineer#26]
# Module: 04
## Lab/Demo: 09
Task: Provision an Azure Synapse Analytics workspace
Step: 05

` cd dp-203/Allfiles/labs/09 ./setup.ps1`

Description of issue
Suspend-AzSynapseSQLPool not loaded from module
![image](https://user-images.githubusercontent.com/104829457/234259448-76c6d74c-c263-4ab6-86de-45b140c15b73.png)

Might be worth investigating - does not impact lab but can cause confusion for those running script independently.

**Comment by weslbo** [comment]
I have seen similar issue today:
<img width="542" alt="image" src="https://user-images.githubusercontent.com/53346841/234516764-2d3a8a2a-02b9-47ff-84cd-13dcc64cfd91.png">

**Comment by molenaar** [comment]
Its related to the Azure Cloud Shell. The az modules are updated. Better to reset your Azure Cloud Shell .

[cid:2265b424-7d34-4614-b857-b19c4a56c5b4]

Then go to advanced and select your existing resource group, storage account and create a new (!) file share.

[cid:4a2c428d-68b8-4ce7-8475-35cbab325845]

Then copy al your files from the old file share to the new file share.

Very, very anoying that the az module is updated and you can't update the module az module in the cloud shell because of dependencies.

Good luck
Marcel

________________________________
Van: Wesley De Bolster ***@***.***>
Verzonden: woensdag 26 april 2023 10:28
Aan: MicrosoftLearning/dp-203-azure-data-engineer ***@***.***>
CC: Subscribed ***@***.***>
Onderwerp: Re: [MicrosoftLearning/dp-203-azure-data-engineer] Lab 9, provisioning setup script throws error (Issue #26)


I have seen similar issue today:
[image]<https://user-images.githubusercontent.com/53346841/234516764-2d3a8a2a-02b9-47ff-84cd-13dcc64cfd91.png>

**Comment by Hendrik1992** [comment]
Hello @molenaar 

Can you please provide some more details on how to reset the Azure Cloud shell? I have the same problem but can not replicate your steps above. 

Thank you very much.

Best,
Hendrik

**Comment by molenaar** [comment]
Mmmm, images weren't uploaded correctly...

Open the CloudShell
![image](https://user-images.githubusercontent.com/10166617/234537554-f8d69631-7b00-4aa0-9423-9f55a79098b9.png)

And first check the name of your storage account connected to your clouddrive
![image](https://user-images.githubusercontent.com/10166617/234538673-5e22655b-e4d5-4e2f-a2e1-75cbb4fccd1c.png)

Then search for your storage account and look for the name of the existing file share
![image](https://user-images.githubusercontent.com/10166617/234539448-aeb0167a-6d9c-4361-8db1-22837c22fb61.png)

Your can see in the screenshot my original file share name and the new file share name (I already resetted my cloud shell so continue with the next steps!)

Then, open the gear of the Cloud Shell and select Reset User Settings
![image](https://user-images.githubusercontent.com/10166617/234540146-4962cb0b-ba7f-4346-af30-bf4cbcb3fa29.png)

Select PowerShell (or Bash, what you prefer)
![image](https://user-images.githubusercontent.com/10166617/234540351-635256af-37f5-4382-8341-9aa0f4be66e7.png)

Select Show Advanced Settings
![image](https://user-images.githubusercontent.com/10166617/234540553-cef6921e-2da0-4fb8-9dce-0de1c2918f8e.png)

Then select your subscription, resourcegroup and storage account and create a new (!) File Share. I choose cloudshell as the new of my new file share

![image](https://user-images.githubusercontent.com/10166617/234541669-294712ab-6135-4605-b206-bd05fc82ad05.png)

Now the Cloud Shell will start and everything should be working fine again!
![image](https://user-images.githubusercontent.com/10166617/234542562-724e2c31-63c3-4f09-9b31-ae99be469255.png)

Good luck
Marcel

**Comment by GraemeMalcolm** [comment]
Thanks @molenaar
